### PR TITLE
Allow for a different component HTML element than a div.

### PR DESCRIPTION
**Pull request by ghost**
I could not help myself to make the tiny change to your code base. It's more or less just one line. As you can see I use '_element' as the attribute name and fall back to `div`. That's more or less it.

I think though it has to be moved out of the attributes and become its own thing.

### CODE REVIEW

**Comment by bencroker** [comment]
Thanks for submitting this, but introducing a configuration option into the attribute options doesn't seem like the best way to solve this.

**Comment by ghost** [comment]
Would you consider a better approach or are you not keen on having such an option at all?

**Comment by bencroker** [comment]
I've considered introducing a fourth parameter for configuration options, as well as the ability to pass in a configuration object with all available options, however neither seem to justify the added complexity in my opinion. What do you have in mind?

**Comment by bencroker** [comment]
After some experimenting I have found that while tags like `ol` will work, `p` tags will not, and will instead silently break things. For that reason I've decided _not_ to add this to core. If you really want to change this behaviour then there is an `EVENT_AFTER_CREATE_COMPONENT` that will allow you to do this:
https://github.com/putyourlightson/craft-sprig/blob/1.0.0-beta.18/src/services/ComponentsService.php#L138-L140

**Pull request closed without merging**
